openapi: 3.0.0

info:
  title: Pizza project API
  version: 1.0.0
  description: |
    Pizza API allows you to remotely manage the pizzeria.
    ### Check out its awesome features:
    * Authorization is required to work with the API. Authorization is done by the bearer-token 😎

tags:
  - name: SimpleRest
    description: Simple rest CRUD API

servers:
  - url: http://localhost:8088/
paths:
  /api/auth/login:
    post:
      description: Get jwt-token
      summary: Authorization method
      tags:
        - Auth
      security: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password

      responses:
        200:
          description: successful authorization
          content:
            application/json:
              schema:
                properties:
                  jwt-token:
                    type: string
        401:
          description: Authentication failed
  /api/users/signup:
    post:
      summary: Registration new user
      description: Get jwt-token
      tags:
        - Auth
      security: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
              required:
                - username
                - password
                - email
      responses:
        200:
          description: Succsessful create new user
          content:
            application/json:
              schema:
                properties:
                  jwt-token:
                    type: string

  /api/users/all:
    get:
      summary: Get all users
      tags:
        - Users
      operationId: getAll
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
        '401':
          description: Access denied

  /api/users/{id}:
    get:
      summary: Get user
      description: Get one by id
      tags:
        - Users
      operationId: get
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200' :
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'

        '401':
          description: Access denied
        '404':
          description: Request failed - No items


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    id:
      in: path
      name: id
      required: true
      description: record id
      schema:
        type: number
  schemas:
    Person:
      type: object
      required:
        - username
        - password
        - email
      properties:
        id:
          type: number
          example: 1
        username:
          type: string
          example: "John Smith"
        password:
          type: string
        email:
          type: string
          example: "test@email.com"
    Persons:
      type: array
      items:
        $ref: '#/components/schemas/Person'


security:
  - bearerAuth: []
